package patches.projects

import jetbrains.buildServer.configs.kotlin.*
import jetbrains.buildServer.configs.kotlin.Project
import jetbrains.buildServer.configs.kotlin.projectFeatures.HashiCorpVaultConnection
import jetbrains.buildServer.configs.kotlin.projectFeatures.hashiCorpVaultConnection
import jetbrains.buildServer.configs.kotlin.ui.*

/*
This patch script was generated by TeamCity on settings change in UI.
To apply the patch, change the root project
accordingly, and delete the patch script.
*/
changeProject(DslContext.projectId) {
    params {
        expect {
            select("sel1", "sel1",
                    options = listOf("sel2", "sel3", "sel4"))
        }
        update {
            select("sel1", "sel1",
                    options = listOf("sel2", "sel3", "sel4"))
        }
    }

    features {
        val feature1 = find<HashiCorpVaultConnection> {
            hashiCorpVaultConnection {
                id = "vaultchubatova"
                name = "HashiCorp Vault"
                url = "https://vault.intellij.net"
                authMethod = appRole {
                    roleId = "secrets-teamcity-qa"
                    secretId = "credentialsJSON:f433e72c-7a67-4e0a-b5f9-12208893b8bb"
                }
            }
        }
        feature1.apply {
        }
    }
}
